name: Daily Contribution

on:
  schedule:
    - cron: "0 15 * * *"  # Every day at 3 PM UTC
permissions:
  contents: write
jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "lealec1234"
          git config --global user.email "lealec1234@gmail.com"

      - name: Make commit
        run: |
          echo "Update at $(date)" >> bot.txt
          git add daily.txt
          git commit -m "Daily update"
          git push







